export const products3 = [
    {
        id: 1,
        name: "Earthen Bottle",
        href: "#",
        price: "$48",
        imageSrc:
            "https://www.ugaoo.com/cdn/shop/products/Krish12Planter-Ivory_3f18466a-68f8-4763-8a18-fe58269b0f6a.jpg?v=1681551837&width=375",
        imageAlt: "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
    },
    {
        id: 2,
        name: "Nomad Tumbler",
        href: "#",
        price: "$35",
        imageSrc:
            "https://www.ugaoo.com/cdn/shop/products/AtlantisPlanter-Teal_dc150664-695d-4972-a996-95f1d6d0dac6.jpg?v=1680515170&width=375",
        imageAlt: "Olive drab green insulated bottle with flared screw lid and flat top.",
    },
    {
        id: 3,
        name: "Focus Paper Refill",
        href: "#",
        price: "$89",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/XL-027.jpg?v=1708075059&width=375",
        imageAlt: "Person using a pen to cross a task off a productivity paper card.",
    },
    {
        id: 4,
        name: "Machined Mechanical Pencil",
        href: "#",
        price: "$35",
        imageSrc:
            "https://www.ugaoo.com/cdn/shop/files/Aimage_ec926ebd-db7c-46a9-a64d-22871d372c02.jpg?v=1705325714&width=375",
        imageAlt: "Hand holding black machined steel mechanical pencil with brass tip and top.",
    },
    {
        id: 1,
        name: "Earthen Bottle",
        href: "#",
        price: "$48",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/DSC_9012.jpg?v=1706609672&width=375",
        imageAlt: "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
    },
    {
        id: 2,
        name: "Nomad Tumbler",
        href: "#",
        price: "$35",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/XL-288.jpg?v=1708075048&width=375",
        imageAlt: "Olive drab green insulated bottle with flared screw lid and flat top.",
    },
    {
        id: 3,
        name: "Focus Paper Refill",
        href: "#",
        price: "$89",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/DSC_3263.jpg?v=1694434958&width=375",
        imageAlt: "Person using a pen to cross a task off a productivity paper card.",
    },
    {
        id: 4,
        name: "Machined Mechanical Pencil",
        href: "#",
        price: "$35",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/DSC_2431.jpg?v=1692966811&width=375",
        imageAlt: "Hand holding black machined steel mechanical pencil with brass tip and top.",
    },
    {
        id: 1,
        name: "Earthen Bottle",
        href: "#",
        price: "$48",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/2_430a864d-f4ed-46d0-b5e6-ff0d55c422db.jpg?v=1706608270&width=375",
        imageAlt: "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
    },
    {
        id: 2,
        name: "Nomad Tumbler",
        href: "#",
        price: "$35",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/DSC_82942.jpg?v=1696240355&width=375",
        imageAlt: "Olive drab green insulated bottle with flared screw lid and flat top.",
    },
    {
        id: 3,
        name: "Focus Paper Refill",
        href: "#",
        price: "$89",
        imageSrc:
            "https://www.ugaoo.com/cdn/shop/products/LagosPlanter-Grey_f26c8dee-c8ce-4e1a-bec7-86006f560c98.jpg?v=1680418283&width=375",
        imageAlt: "Person using a pen to cross a task off a productivity paper card.",
    },
    {
        id: 4,
        name: "Machined Mechanical Pencil",
        href: "#",
        price: "$35",
        imageSrc: "https://www.ugaoo.com/cdn/shop/files/Smallpot-164.jpg?v=1704867612&width=375",
        imageAlt: "Hand holding black machined steel mechanical pencil with brass tip and top.",
    },
    // More products...
];
